export async function GET() {
    return new Response(
        `
		<?xml version="1.0" encoding="UTF-8" ?>
		<urlset
			xmlns="https://www.sitemaps.org/schemas/sitemap/0.9"
			xmlns:xhtml="https://www.w3.org/1999/xhtml"
			xmlns:mobile="https://www.google.com/schemas/sitemap-mobile/1.0"
			xmlns:news="https://www.google.com/schemas/sitemap-news/0.9"
			xmlns:image="https://www.google.com/schemas/sitemap-image/1.1"
			xmlns:video="https://www.google.com/schemas/sitemap-video/1.1"
		>
            <url>
                <loc>https://speakingpass.com</loc>
                <lastmod>2024-06-13</lastmod>
                <priority>1.0</priority>
                <changefreq>weekly</changefreq>
            </url>
            <url>
                <loc>https://speakingpass.com/part1</loc>
                <lastmod>2024-06-13</lastmod>
                <priority>0.9</priority>
                <changefreq>weekly</changefreq>
            </url>
            <url>
                <loc>https://speakingpass.com/part1/Study</loc>
                <lastmod>2024-06-13</lastmod>
                <priority>0.8</priority>
                <changefreq>weekly</changefreq>
            </url>
            <url>
                <loc>https://speakingpass.com/part1/Work</loc>
                <lastmod>2024-06-13</lastmod>
                <priority>0.8</priority>
                <changefreq>weekly</changefreq>
            </url>
            <url>
                <loc>https://speakingpass.com/part1/Accommodation</loc>
                <lastmod>2024-06-13</lastmod>
                <priority>0.8</priority>
                <changefreq>weekly</changefreq>
            </url>
            <url>
                <loc>https://speakingpass.com/part1/Hometown</loc>
                <lastmod>2024-06-13</lastmod>
                <priority>0.8</priority>
                <changefreq>weekly</changefreq>
            </url>
            <url>
                <loc>https://speakingpass.com/part2&3/Person/1</loc>
                <lastmod>2024-06-13</lastmod>
                <priority>0.9</priority>
                <changefreq>weekly</changefreq>
            </url>
            <url>
                <loc>https://speakingpass.com/part2&3/Object/1</loc>
                <lastmod>2024-06-13</lastmod>
                <priority>0.8</priority>
                <changefreq>weekly</changefreq>
            </url>
            <url>
                <loc>https://speakingpass.com/part2&3/Activity/1</loc>
                <lastmod>2024-06-13</lastmod>
                <priority>0.8</priority>
                <changefreq>weekly</changefreq>
            </url>
            <url>
                <loc>https://speakingpass.com/part2&3/Place/1</loc>
                <lastmod>2024-06-13</lastmod>
                <priority>0.8</priority>
                <changefreq>weekly</changefreq>
            </url>
        </urlset>
        `.trim(),
        {
            headers: {
                'Content-Type': 'application/xml'
            }
        }
    );
}